name: rollbar
version: 0.3.0
authors:
  - Anton Astashov <anton.astashov@gmail.com>
  - Dan Schultz <schultz.t.dan@gmail.com>
description: A package for logging application errors and messages to Rollbar.
homepage: http://www.github.com/Mixbook/rollbar.dart
dependencies:
  stack_trace: '>=1.0.2 <2.0.0'
  logging: '>=0.9.1 <0.10.0'
  http: '>=0.11.1'
